// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

//每个 *.proto 文件可以指定 package 作为生成语言的 namespace

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_Skills int32

const (
	Person_GOLANG Person_Skills = 0
	Person_PYTHON Person_Skills = 1
	Person_JAVA   Person_Skills = 2
	Person_RUST   Person_Skills = 3
	Person_CPP    Person_Skills = 4
)

var Person_Skills_name = map[int32]string{
	0: "GOLANG",
	1: "PYTHON",
	2: "JAVA",
	3: "RUST",
	4: "CPP",
}

var Person_Skills_value = map[string]int32{
	"GOLANG": 0,
	"PYTHON": 1,
	"JAVA":   2,
	"RUST":   3,
	"CPP":    4,
}

func (x Person_Skills) String() string {
	return proto.EnumName(Person_Skills_name, int32(x))
}

func (Person_Skills) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}

//message 用来定义一个数据结构
//repeated 的使用：被 repeated 标识的字段可以理解为是一个数组
//enum 类型使用：枚举用来表示一定范围内具有相同属性的值
//message 类型的使用： message 在定义过程中是可以声明自己定义的 message 类型
//map 类型的使用：message 定义时可以使用 map 类型
type Person struct {
	Age                  int64                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Realname             string                 `protobuf:"bytes,2,opt,name=realname,proto3" json:"realname,omitempty"`
	Sex                  string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Vehicle              []string               `protobuf:"bytes,4,rep,name=vehicle,proto3" json:"vehicle,omitempty"`
	Skill                Person_Skills          `protobuf:"varint,5,opt,name=skill,proto3,enum=example.Person_Skills" json:"skill,omitempty"`
	WorkDay              *WorkDays              `protobuf:"bytes,6,opt,name=workDay,proto3" json:"workDay,omitempty"`
	Dept                 map[string]*Department `protobuf:"bytes,7,rep,name=dept,proto3" json:"dept,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *Person) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Person) GetVehicle() []string {
	if m != nil {
		return m.Vehicle
	}
	return nil
}

func (m *Person) GetSkill() Person_Skills {
	if m != nil {
		return m.Skill
	}
	return Person_GOLANG
}

func (m *Person) GetWorkDay() *WorkDays {
	if m != nil {
		return m.WorkDay
	}
	return nil
}

func (m *Person) GetDept() map[string]*Department {
	if m != nil {
		return m.Dept
	}
	return nil
}

type WorkDays struct {
	Day                  int32    `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkDays) Reset()         { *m = WorkDays{} }
func (m *WorkDays) String() string { return proto.CompactTextString(m) }
func (*WorkDays) ProtoMessage()    {}
func (*WorkDays) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *WorkDays) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkDays.Unmarshal(m, b)
}
func (m *WorkDays) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkDays.Marshal(b, m, deterministic)
}
func (m *WorkDays) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkDays.Merge(m, src)
}
func (m *WorkDays) XXX_Size() int {
	return xxx_messageInfo_WorkDays.Size(m)
}
func (m *WorkDays) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkDays.DiscardUnknown(m)
}

var xxx_messageInfo_WorkDays proto.InternalMessageInfo

func (m *WorkDays) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type Department struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{2}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("example.Person_Skills", Person_Skills_name, Person_Skills_value)
	proto.RegisterType((*Person)(nil), "example.Person")
	proto.RegisterMapType((map[string]*Department)(nil), "example.Person.DeptEntry")
	proto.RegisterType((*WorkDays)(nil), "example.WorkDays")
	proto.RegisterType((*Department)(nil), "example.Department")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbf, 0xf9, 0xdd, 0x4c, 0xbf, 0x48, 0x5c, 0x41, 0xd6, 0xe2, 0x61, 0xc9, 0x29, 0xa2,
	0xe6, 0x10, 0x2f, 0x22, 0x78, 0x28, 0x56, 0x2a, 0x52, 0xda, 0xb0, 0xad, 0x8a, 0xc7, 0xd5, 0x0e,
	0x5a, 0x9a, 0x26, 0x21, 0x89, 0xb5, 0xfd, 0xd3, 0xbd, 0xc9, 0xee, 0xda, 0x08, 0xde, 0x3e, 0x33,
	0xf3, 0x98, 0x79, 0x8f, 0x81, 0xff, 0x25, 0x56, 0x75, 0x91, 0xc7, 0x65, 0x55, 0x34, 0x05, 0xf1,
	0x70, 0x23, 0x56, 0x65, 0x86, 0xe1, 0x97, 0x09, 0x6e, 0xaa, 0x26, 0x24, 0x00, 0x4b, 0xbc, 0x21,
	0x35, 0x98, 0x11, 0x59, 0x5c, 0x22, 0xe9, 0x41, 0xa7, 0x42, 0x91, 0xe5, 0x62, 0x85, 0xd4, 0x64,
	0x46, 0xe4, 0xf3, 0xb6, 0x96, 0xea, 0x1a, 0x37, 0xd4, 0x52, 0x6d, 0x89, 0x84, 0x82, 0xb7, 0xc6,
	0xf7, 0xc5, 0x6b, 0x86, 0xd4, 0x66, 0x56, 0xe4, 0xf3, 0x5d, 0x49, 0xce, 0xc0, 0xa9, 0x97, 0x8b,
	0x2c, 0xa3, 0x0e, 0x33, 0xa2, 0xbd, 0xe4, 0x30, 0xfe, 0xb9, 0x1e, 0xeb, 0xcb, 0xf1, 0x54, 0x0e,
	0x6b, 0xae, 0x45, 0xe4, 0x14, 0xbc, 0xcf, 0xa2, 0x5a, 0x0e, 0xc4, 0x96, 0xba, 0xcc, 0x88, 0xba,
	0xc9, 0x7e, 0xab, 0x7f, 0xd2, 0xfd, 0x9a, 0xef, 0x14, 0xe4, 0x1c, 0xec, 0x39, 0x96, 0x0d, 0xf5,
	0x98, 0x15, 0x75, 0x93, 0xa3, 0xbf, 0x9b, 0x07, 0x58, 0x36, 0xb7, 0x79, 0x53, 0x6d, 0xb9, 0x92,
	0xf5, 0x46, 0xe0, 0xb7, 0x2d, 0x19, 0x61, 0x89, 0x5b, 0x15, 0xd8, 0xe7, 0x12, 0xc9, 0x09, 0x38,
	0x6b, 0x91, 0x7d, 0xe8, 0xb4, 0xdd, 0xe4, 0xa0, 0x5d, 0x37, 0xc0, 0x52, 0x54, 0xcd, 0x0a, 0xf3,
	0x86, 0x6b, 0xc5, 0x95, 0x79, 0x69, 0x84, 0xd7, 0xe0, 0x6a, 0xeb, 0x04, 0xc0, 0x1d, 0x4e, 0x46,
	0xfd, 0xf1, 0x30, 0xf8, 0x27, 0x39, 0x7d, 0x9e, 0xdd, 0x4d, 0xc6, 0x81, 0x41, 0x3a, 0x60, 0xdf,
	0xf7, 0x1f, 0xfb, 0x81, 0x29, 0x89, 0x3f, 0x4c, 0x67, 0x81, 0x45, 0x3c, 0xb0, 0x6e, 0xd2, 0x34,
	0xb0, 0xc3, 0x63, 0xe8, 0xec, 0x02, 0x49, 0x2f, 0x73, 0xa1, 0xbd, 0x38, 0x5c, 0x62, 0xc8, 0x00,
	0x7e, 0xaf, 0x12, 0x02, 0xb6, 0x7a, 0x83, 0x36, 0xab, 0xf8, 0xc5, 0x55, 0xbf, 0xbc, 0xf8, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x95, 0x3e, 0x98, 0xaf, 0xdb, 0x01, 0x00, 0x00,
}
